server:
  port: 8080
  servlet: 
    context-path: /hievents
    session:
      cookie:
        secure: true
        http-only: true

spring:  
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://mysql:3306/hievents
    username: hievents
    password: hievents
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
                
hievents:
  listMaxSize: 100
  security:
    encryptionSalt: TopSecret



